"""create hospitals table

Revision ID: 7349c7cc195d
Revises: ee7765c3e4c0
Create Date: 2026-07-27 01:33:08.742410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7349c7cc195d'
down_revision: Union[str, Sequence[str], None] = 'ee7765c3e4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'hospital_id')
    # ### end Alembic commands ###
